---
repos:
  - repo: local
    hooks:
      - id: run-checks
        name: Run Checks
        description: Ensure that all checks pass before committing
        language: system
        always_run: true
        pass_filenames: false
        entry: uv run invoke check

  - repo: local
    hooks:
      - id: run-tests
        name: Run Unit Tests
        description: Ensure that unit tests pass before committing
        language: system
        always_run: true
        pass_filenames: false
        entry: uv run invoke test

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.18  # uv version
    hooks:
      - id: uv-lock
        description: Ensure uv's lock file matches deps in pyproject.toml
