---
API_HOST: "0.0.0.0"
API_PORT: 8080
BOT_TOKEN:
EMBED_MAX_LENGTH: 1024
CHANNELS:
  ANNOUNCEMENTS: 1113007584702627911
  BOT_LOGS: 1390267799863165038
  BOT_PLAYGROUND: 1296529518793588748
  GITHUB: 1522491309003243660
  MOUSETRAP: 1319726258493591612
  RULES: 1229425258747138180
DRY_RUN: false
DRY_RUN_GITHUB: false
DRY_RUN_YOUTUBE: false
GITHUB:
  EVENTS:
    ISSUE_COMPLETED: true
    ISSUE_NOT_PLANNED: true
    ISSUE_OPENED: true
    PR_CLOSED: true
    PR_MERGED: true
    PR_OPENED: true
    PR_REVIEW_APPROVED: false
    PR_REVIEW_CHANGES_REQUESTED: true
    PR_REVIEW_COMMENTED: false
  POLL_MINUTES: 5
  REPO: "JamesTurland/JimsGarage"
  TOKEN:                       # overridden by env GITHUB_TOKEN
GUILDS:
  JIMS_GARAGE: 1109224479281905787
LOG_CHANNEL:
LOG_DIR: "log"
LOG_FILE: "bot.log"
LOG_LEVEL_FILE: "DEBUG"
LOG_LEVEL_STDOUT: "INFO"
ROLES:
  ADMIN: 1230087912159449108
  BOTS: 1296533955654451270
  GARAGE_MEMBER: 1296535672223698985
  JIMS_GARAGE: 1316312797419929702
  MOD: 1205631095547105290
  VIP: 1128425498540785705
TIMEZONE: "UTC"
YOUTUBE_FEEDS:
  JIMS_GARAGE: "https://www.youtube.com/feeds/videos.xml?channel_id=UCUUTdohVElFLSP4NBnlPEwA"
  TECH_BENCH: "https://www.youtube.com/feeds/videos.xml?channel_id=UCT5B7jBug46N7abnl_izt5w"
